language: groovy
matrix:
  include:
  - jdk: openjdk11
    env: TEST_ALL_CONTAINERS="['tomcat10']" GRADLE_VERSION="5.6.4"
  - jdk: openjdk15
    env: TEST_ALL_CONTAINERS="['tomcat10']" GRADLE_VERSION="6.6.1"
  - jdk: openjdk11
    env: TEST_ALL_CONTAINERS="['tomcat10']" GRADLE_VERSION="6.6.1"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper
before_install:
  - chmod +x gradlew
  - sudo apt-get -qq update
  - sudo apt-get install -y zip curl locate libbcprov-java
before_script:
  - "export DISPLAY=:99.0"
services:
  - xvfb
install:
  - true
script:
  - |
    set -e
    ./gradlew wrapper --gradle-version ${GRADLE_VERSION} --distribution-type all
    ./gradlew build
    if [[ ! -z $TEST_ALL_CONTAINERS && ( -z $TEST_ALL || "${TRAVIS_REPO_SLUG}" == "gretty-gradle-plugin/gretty" ) ]]; then
      cd integrationTests
      ../gradlew -PgeckoDriverPlatform=linux64 -PgeckoDriverVersion=0.27.0 -PtestAllContainers=${TEST_ALL_CONTAINERS} testAll
      cd ..
    fi
    set +e
env:
  global:
    - secure: "WoVyzk7PO/bzFjEaLuGmi4s9XLoKdkUoilQ+k6FDTqhjFCSqNeRHl/gQgYslnv3hw1fIz9yu0n9QAQCAwMUlG6shDDIxjiHSVakS1xvuYSfYa9y+s8mpl1IdLur2OL41mZZdvW/NOy5Qmk9Py3Z2oLG3oV5j7pwyzsBOYQ+589EdlunwdM9qZVhD0CmQLSdcG2Ufvja1E86Zf/KE7AumRmWh2wjhRVTKv7n4Dp/fnHl3HlJLeQHCORjk/elTZrzrab5RshJDr8Q72WMm7ZtlAvbxNlIajlnpAZprV1QEjsP+907/QJ5wPA+XyZUxnDEcN9oewqwByS57ICUC8uHWdEBfSl90gogrhDxLlJB4wW7L7N3DgkyUT+AxhrZU7DQkPuQO40BAUsdHpxgoeqOLU6J5vmVZ5YL6Mp9ulL8orYL8RFLEvrOsrSHgRIP6tQ3jjVan95WHQTvKhWbAgBTL2hZLNIJm7SrbXEb4vyEVIRZgZx9JPVjPm3rc8eVYLgDfstEe4vrL/3tCiJVzCSWvYhyfUrVNNvZgIM3AeMS7fs0YBLt3SvxOPDULxN2digScM834XJNfGBtBiTZt9HVE0uasNxbCHhGKmDQqq96obc38vQzTrH+ypclfG4l1O3wHhfCN+D4rJqRtajE2lhvABDSwp+g5nk7U1TMPKAc4+9U="
    - secure: "YIgwBJa9aVg9FQUwQzmw6utO17Jp/ZiwBJtfUP/xps9zmhtND7e0cZfLimljjbyfJ8CIPhmF2xd7Eu7aXNxRXe3p50/cok4fcfVtPX/Tirn1l5CM2IG2MJpABOpJdED71GFNkuej6gMhR461RfNn2c7XP1mTdO5cB7dGEOUy5ZnabyRHdO4IjH313LzA7fIGCR0cmqAepcVObRlxnbDG/JRGJA2icvR4t6HsI8M+Facslr/9rxt+BqECixglvzn3+M3zz34cJm9Y9hUDU1nPhBvwXba+P5MSj9Yy5ScW4CuOvDjud5bpZFaUsbCBeg0FMDPzLnynWSYUuE14RxydZ+tEuaiwPvVD+1/9uHB5szPueoOo2uVaSo47RMcjrwDwIinxYDU1/lkrTWxyIGyfFRWzO+CiIjPoyCoAfhWOLwiTMInNm+0BS77SYj1HnhsPGWnnODhUDhRt86ZbA0vrhiMZMq8TasvpWXiAndcDIRXYeXYRG6SBwl8bvsDwao5JkL2m3ufM/Y6c3u8RiC28g65toQ3d/33CIinZmEOEzMWvHH4cIaMFt4hzYnTbj9ug57XIqdH791kA6wtAsHNLHR30ZdRVMMGzm8IlaDM4t6btt0HCl+8lJBwkmKqik0z5RW/tJIM400cP5kfSNlFPcXTbLIV+HSQ2fH6KwsYfxgI="
    - JAVA_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1G"

# FIXME revisit deployment options: Jetty 9.x fell out-of-scope (#165)
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PbintrayRepo=${BINTRAY_REPO} -PbintrayPackage=${BINTRAY_PACKAGE}
    on:
      repo: gretty-gradle-plugin/gretty
      branch: master
      jdk: openjdk8
      condition: $TEST_ALL_CONTAINERS =~ "jetty9.4'"
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PbintrayRepo=${BINTRAY_REPO} -PbintrayPackage=${BINTRAY_PACKAGE}
    on:
      repo: gretty-gradle-plugin/gretty
      branch: gretty-2.x
      jdk: openjdk8
      condition: $TEST_ALL_CONTAINERS =~ "jetty9'"
